Adding linter to devel
aleksander-git/data-analyzer pull request #8
Opened 2024-05-20 20:29 UTC by KFN002

Pull request to merge dev-linter into devel

2024-05-27 14:15 UTC, kvizyx requested changes

2024-05-27 14:15 UTC, kvizyx commented on go.work
Зачем нам сейчас ворк файл?

2024-05-27 14:15 UTC, kvizyx commented on .github/workflows/golangci-lint.yml
> +        run: go mod tidy
Точно ли нужно tidy делать? В теории же может что-то поломаться. Это лучше делать локально как по мне.

2024-05-27 14:15 UTC, kvizyx commented on go.work
Зачем нам сейчас ворк файл?

2024-05-27 16:49 UTC, KFN002 commented on .github/workflows/golangci-lint.yml
> +        run: go mod tidy
![image](https://github.com/aleksander-git/data-analyzer/assets/119512897/0fca1f2f-dffd-4b06-864b-70b7ce6451d0)

2024-05-27 17:10 UTC, KFN002 commented on .github/workflows/golangci-lint.yml
> +        run: go mod tidy
Removed go.work

2024-05-27 17:11 UTC, KFN002 commented on .github/workflows/golangci-lint.yml
> +        run: go mod tidy
Please, do not change the code yourself, text the author first!

2024-05-28 13:03 UTC, LLIEPJIOK reviewed
Ошибок не заметил. Хорошая настройка линтера

2024-05-28 18:53 UTC, kvizyx approved these changes

2024-05-30 12:38 UTC, LLIEPJIOK approved these changes

2024-05-30 15:10 UTC, merged